/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zofia.gui;

import com.zofia.dummyclasses.Canvas;
import com.zofia.dummyclasses.Image;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author zofia
 */
public class CanvasPanel extends javax.swing.JPanel {
    private Canvas selected;
    private Image selectedImage;
    private List<Image> canvasImages;
    private List<Canvas> canvases;
    private List<ImagePanel> images;
    private List<JPanel> panel;
    private String[] imageTitle;
    private Colors colors;
    private boolean change;
    /**
     * Creates a new Panel for an specific canvas
     * @param canvases
     */
    public CanvasPanel(List<Canvas> canvases) {
        initComponents();
        this.canvases = canvases;
        initValues();
        fillTabData();
        fillBoxes();
        setValues();
        setCurrentImage(0, 0);
        change = true;
    }
    
    private void initValues() {
        this.selected = canvases.get(0);
        this.canvasImages = selected.getTime().getImages();
        this.images = new ArrayList<>();
        this.imageTitle = new String[canvases.size()];
        this.panel = new ArrayList<>();
        this.selectedImage = canvasImages.get(0);
        addPanels();
    }
    
    private void fillTabData() {
        for (int i = 0; i < imageTitle.length; i++) {
            imageTitle[i] = canvases.get(i).getId();
            panel.add(new JPanel());
            tabbedPanel.addTab(imageTitle[i], panel.get(i));
        }
    }
    
    private void addPanels() {
        for(Canvas canvas : canvases) {
            for(Image image : canvas.getTime().getImages()) {
                image.setImage(new ImagePanel(this, canvas.getColor(),canvas.getSquare()));
                images.add(image.getImage());
            }
        }
    }
    
    private void setCurrentImage(int index, int panel) {
        ImagePanel image = canvasImages.get(index).getImage();
        image.setBorder(false);
        this.panel.get(panel).removeAll();
        JScrollPane scroll = new JScrollPane();
        scroll.setViewportView(image);
        this.panel.get(panel).setLayout(new BorderLayout());
        this.panel.get(panel).add(scroll, BorderLayout.CENTER);
        this.panel.get(panel).repaint();
        this.panel.get(panel).revalidate();
    }
    
    private void fillBoxes() {
        change = false;
        canvasImages = selected.getTime().getImages();
        this.imageBox.removeAllItems();
        this.start.removeAllItems();
        for(Image image : canvasImages) {
            imageBox.addItem(image.getId());
            start.addItem(image.getId());
            end.addItem(image.getId());
        }
        setInitialBoxesValues();
        addColorComboBox();
        change = true;
    }
    
    private void setValues() {
        amountField.setText(String.valueOf(canvasImages.size()));
        durationField.setText(String.valueOf(selectedImage.getDuration()));
    }
    
    public void addColorComboBox(){
        colors = new Colors(selected.getColorsTable());
        colorPanel.removeAll();
        colorPanel.add(colors);
        colorPanel.repaint();
        colorPanel.revalidate();
        colors.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                    selectedButton.setBackground(colors.getSelectedColor());
           }
        });     
    }
    
    private void setInitialBoxesValues() {
        imageBox.setSelectedIndex(0);
        start.setSelectedItem(selected.getTime().getStart());
        end.setSelectedItem(selected.getTime().getEnd());
    }

    public JCheckBox getEraser() {
        return eraser;
    }

    public JButton getSelectedButton() {
        return selectedButton;
    }
    
    private void setSelectedImage(String id) {
        int index = 0;
        for(Image image : selected.getTime().getImages()) {
            if(image.getId().equals(id)) {
                selectedImage = image;
            }
            index++;
        }
        setCurrentImage(index-1, tabbedPanel.getSelectedIndex());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        propertiesPanel = new javax.swing.JPanel();
        amountLabel = new javax.swing.JLabel();
        starLabel = new javax.swing.JLabel();
        endLabel = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        firstSeparator = new javax.swing.JSeparator();
        imageLabel = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();
        imageBox = new javax.swing.JComboBox<>();
        durationField = new javax.swing.JTextField();
        start = new javax.swing.JComboBox<>();
        end = new javax.swing.JComboBox<>();
        secondSeparator = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        colorLabel = new javax.swing.JLabel();
        selectedButton = new javax.swing.JButton();
        eraser = new javax.swing.JCheckBox();
        colorPanel = new javax.swing.JPanel();
        colorPicker = new javax.swing.JComboBox<>();
        centralPanel = new javax.swing.JPanel();
        tabbedPanel = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(247, 237, 226));
        setPreferredSize(new java.awt.Dimension(1040, 547));

        propertiesPanel.setBackground(new java.awt.Color(247, 237, 226));
        propertiesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Properties", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        propertiesPanel.setForeground(new java.awt.Color(102, 102, 102));

        amountLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        amountLabel.setText("Amount:");

        starLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        starLabel.setText("Start:");

        endLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        endLabel.setText("End:");

        amountField.setEnabled(false);

        firstSeparator.setForeground(new java.awt.Color(102, 102, 102));
        firstSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        imageLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        imageLabel.setText("Image:");

        durationLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        durationLabel.setText("Duration:");

        imageBox.setBackground(new java.awt.Color(255, 255, 255));
        imageBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        imageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        imageBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                imageBoxItemStateChanged(evt);
            }
        });
        imageBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageBoxActionPerformed(evt);
            }
        });

        start.setBackground(new java.awt.Color(255, 255, 255));
        start.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        end.setBackground(new java.awt.Color(255, 255, 255));
        end.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        end.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout propertiesPanelLayout = new javax.swing.GroupLayout(propertiesPanel);
        propertiesPanel.setLayout(propertiesPanelLayout);
        propertiesPanelLayout.setHorizontalGroup(
            propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(propertiesPanelLayout.createSequentialGroup()
                        .addComponent(amountLabel)
                        .addGap(3, 3, 3)
                        .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(propertiesPanelLayout.createSequentialGroup()
                        .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(starLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(endLabel))
                        .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(propertiesPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(propertiesPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(10, 10, 10)
                .addComponent(firstSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(durationLabel)
                    .addComponent(imageLabel)
                    .addComponent(imageBox, 0, 90, Short.MAX_VALUE)
                    .addComponent(durationField))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        propertiesPanelLayout.setVerticalGroup(
            propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(firstSeparator)
            .addGroup(propertiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(propertiesPanelLayout.createSequentialGroup()
                        .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountLabel)
                            .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(starLabel)
                            .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endLabel)
                            .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(propertiesPanelLayout.createSequentialGroup()
                        .addComponent(imageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(durationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(durationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        secondSeparator.setBackground(new java.awt.Color(247, 237, 226));
        secondSeparator.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Colors", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Color picker:");

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));

        colorLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        colorLabel.setText("Selected color:");

        selectedButton.setBackground(new java.awt.Color(255, 255, 255));

        eraser.setBackground(new java.awt.Color(247, 237, 226));
        eraser.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        eraser.setText("Eraser selected");
        eraser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        colorPanel.setBackground(new java.awt.Color(247, 237, 226));
        colorPanel.setLayout(new java.awt.GridBagLayout());

        colorPicker.setBackground(new java.awt.Color(255, 255, 255));
        colorPicker.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        colorPicker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 136;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        colorPanel.add(colorPicker, gridBagConstraints);

        javax.swing.GroupLayout secondSeparatorLayout = new javax.swing.GroupLayout(secondSeparator);
        secondSeparator.setLayout(secondSeparatorLayout);
        secondSeparatorLayout.setHorizontalGroup(
            secondSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondSeparatorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(secondSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(secondSeparatorLayout.createSequentialGroup()
                        .addGroup(secondSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eraser)
                            .addComponent(jLabel3)
                            .addGroup(secondSeparatorLayout.createSequentialGroup()
                                .addComponent(colorLabel)
                                .addGap(36, 36, 36)
                                .addComponent(selectedButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(colorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        secondSeparatorLayout.setVerticalGroup(
            secondSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondSeparatorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(colorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(secondSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(secondSeparatorLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(colorLabel)))
                .addGap(23, 23, 23)
                .addComponent(eraser)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        centralPanel.setOpaque(false);

        tabbedPanel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedPanelStateChanged(evt);
            }
        });

        javax.swing.GroupLayout centralPanelLayout = new javax.swing.GroupLayout(centralPanel);
        centralPanel.setLayout(centralPanelLayout);
        centralPanelLayout.setHorizontalGroup(
            centralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
        );
        centralPanelLayout.setVerticalGroup(
            centralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanel)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secondSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propertiesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(centralPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(propertiesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(secondSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addComponent(centralPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imageBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageBoxActionPerformed
        // TODO add your handling code here:
      /*Do nothing :/*/
    }//GEN-LAST:event_imageBoxActionPerformed

    private void imageBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_imageBoxItemStateChanged
        // TODO add your handling code here:
        if(imageBox.getSelectedIndex() >= 0) {
            if(change) {
                String value = (String) imageBox.getModel().getSelectedItem();
                setSelectedImage(value);
                setValues();
            }
        }
        
    }//GEN-LAST:event_imageBoxItemStateChanged

    private void tabbedPanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedPanelStateChanged
        // TODO add your handling code here:
        selected = canvases.get(tabbedPanel.getSelectedIndex());
        fillBoxes();
        addColorComboBox();
        setValues();
        selectedButton.setBackground(colors.getSelectedColor());
        eraser.setSelected(false);
        setCurrentImage(0, tabbedPanel.getSelectedIndex());
    }//GEN-LAST:event_tabbedPanelStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JPanel centralPanel;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JPanel colorPanel;
    private javax.swing.JComboBox<String> colorPicker;
    private javax.swing.JTextField durationField;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JComboBox<String> end;
    private javax.swing.JLabel endLabel;
    private javax.swing.JCheckBox eraser;
    private javax.swing.JSeparator firstSeparator;
    private javax.swing.JComboBox<String> imageBox;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel propertiesPanel;
    private javax.swing.JPanel secondSeparator;
    private javax.swing.JButton selectedButton;
    private javax.swing.JLabel starLabel;
    private javax.swing.JComboBox<String> start;
    private javax.swing.JTabbedPane tabbedPanel;
    // End of variables declaration//GEN-END:variables
}
