/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zofia.gui;

import com.zofia.drivers.CanvasDriver;
import com.zofia.drivers.FileDriver;
import javax.swing.JOptionPane;

/**
 *
 * @author zofia
 */
public class GraphicalEditorFrame extends javax.swing.JInternalFrame {
    /**
     * Creates new form GraphicalEditorFrame
     */
    private FileDriver fileDriver;
    private CanvasDriver driver;
    private CanvasPanel panel;
    
    
    public GraphicalEditorFrame(CanvasDriver driver) {
        initComponents();
        this.driver = driver;
        initValues();
        addCanvas();
    }

    private void initValues() {
        this.fileDriver = new FileDriver();
        this.panel = new CanvasPanel(driver.getCanvases());
    }
    
    private void addCanvas() {
        tabbedPanel.addTab("Editor", panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanel = new javax.swing.JTabbedPane();
        bar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveItem = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        userManualItem = new javax.swing.JMenuItem();
        techManualItem = new javax.swing.JMenuItem();
        about = new javax.swing.JMenuItem();

        setPreferredSize(new java.awt.Dimension(1050, 600));

        bar.setBackground(new java.awt.Color(132, 165, 157));

        fileMenu.setText("File");

        saveItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save16.png"))); // NOI18N
        saveItem.setText("Save");
        fileMenu.add(saveItem);

        bar.add(fileMenu);

        help.setText("Help");

        userManualItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        userManualItem.setText("User Manual");
        userManualItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManualItemActionPerformed(evt);
            }
        });
        help.add(userManualItem);

        techManualItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tech.png"))); // NOI18N
        techManualItem.setText("Technical Manual");
        techManualItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                techManualItemActionPerformed(evt);
            }
        });
        help.add(techManualItem);

        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about.png"))); // NOI18N
        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        help.add(about);

        bar.add(help);

        setJMenuBar(bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
        String information = "Desarrollado por: Sofia Quintana\n" + 
                             "Organizacion: USAC-CUNOC\n";
        JOptionPane.showMessageDialog(this, information, "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aboutActionPerformed

    private void userManualItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManualItemActionPerformed
        // TODO add your handling code here:
        fileDriver.openPDF("user_manual.pdf");
    }//GEN-LAST:event_userManualItemActionPerformed

    private void techManualItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_techManualItemActionPerformed
        // TODO add your handling code here:
        fileDriver.openPDF("tech_manual.pdf");
    }//GEN-LAST:event_techManualItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JMenuBar bar;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu help;
    private javax.swing.JMenuItem saveItem;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JMenuItem techManualItem;
    private javax.swing.JMenuItem userManualItem;
    // End of variables declaration//GEN-END:variables
}
