
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.zofia.parsers.JSON;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tamaño = 4;
  public static final int CURLYBRACESC = 30;
  public static final int acumular = 12;
  public static final int BRACKETO = 33;
  public static final int mostrarNaves = 14;
  public static final int planetas = 24;
  public static final int produccion = 16;
  public static final int FACIL = 27;
  public static final int PLANETAS = 18;
  public static final int INTEGER = 39;
  public static final int alAzar = 7;
  public static final int finalizacion = 17;
  public static final int NEUTRALES = 13;
  public static final int BRACKETC = 34;
  public static final int DIFICIL = 28;
  public static final int mostrarEstadisticas = 15;
  public static final int MAPA = 2;
  public static final int COMMA = 32;
  public static final int planetasNeutrales = 10;
  public static final int ID = 38;
  public static final int PLAYER = 37;
  public static final int EOF = 0;
  public static final int TRUE = 8;
  public static final int nombre = 19;
  public static final int COMILLA = 35;
  public static final int error = 1;
  public static final int PLANETAS_NEUTRALES = 22;
  public static final int NAME = 36;
  public static final int mapaCiego = 11;
  public static final int HUMANO = 26;
  public static final int id = 3;
  public static final int COLON = 31;
  public static final int tipo = 25;
  public static final int filas = 5;
  public static final int JUGADORES = 23;
  public static final int columnas = 6;
  public static final int naves = 20;
  public static final int CURLYBRACESO = 29;
  public static final int PERCENTAGE = 40;
  public static final int FALSE = 9;
  public static final int porcentajeMuertes = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAPA",
  "id",
  "tamaño",
  "filas",
  "columnas",
  "alAzar",
  "TRUE",
  "FALSE",
  "planetasNeutrales",
  "mapaCiego",
  "acumular",
  "NEUTRALES",
  "mostrarNaves",
  "mostrarEstadisticas",
  "produccion",
  "finalizacion",
  "PLANETAS",
  "nombre",
  "naves",
  "porcentajeMuertes",
  "PLANETAS_NEUTRALES",
  "JUGADORES",
  "planetas",
  "tipo",
  "HUMANO",
  "FACIL",
  "DIFICIL",
  "CURLYBRACESO",
  "CURLYBRACESC",
  "COLON",
  "COMMA",
  "BRACKETO",
  "BRACKETC",
  "COMILLA",
  "NAME",
  "PLAYER",
  "ID",
  "INTEGER",
  "PERCENTAGE"
  };
}

