
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.zofia.parsers.SAVING;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int acumular = 13;
  public static final int SLASH = 35;
  public static final int mostrarNaves = 15;
  public static final int produccion = 17;
  public static final int FACIL = 30;
  public static final int PLANETAS = 19;
  public static final int INTEGER = 40;
  public static final int alAzar = 8;
  public static final int finalizacion = 18;
  public static final int NEUTRALES = 14;
  public static final int DIFICIL = 31;
  public static final int mostrarEstadisticas = 16;
  public static final int MAPA = 2;
  public static final int MAYORQUE = 33;
  public static final int CONQUISTADO = 23;
  public static final int planetasNeutrales = 11;
  public static final int ID = 39;
  public static final int propietario = 25;
  public static final int PLAYER = 38;
  public static final int EOF = 0;
  public static final int EQUAL = 36;
  public static final int SIZE = 5;
  public static final int TRUE = 9;
  public static final int nombre = 20;
  public static final int NEUTRAL = 24;
  public static final int error = 1;
  public static final int color = 32;
  public static final int NAME = 37;
  public static final int JUEGO = 3;
  public static final int MENORQUE = 34;
  public static final int mapaCiego = 12;
  public static final int HUMANO = 29;
  public static final int id = 4;
  public static final int tipo = 28;
  public static final int JUGADOR = 27;
  public static final int filas = 6;
  public static final int JUGADORES = 26;
  public static final int columnas = 7;
  public static final int naves = 21;
  public static final int PERCENTAGE = 41;
  public static final int FALSE = 10;
  public static final int porcentajeMuertes = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAPA",
  "JUEGO",
  "id",
  "SIZE",
  "filas",
  "columnas",
  "alAzar",
  "TRUE",
  "FALSE",
  "planetasNeutrales",
  "mapaCiego",
  "acumular",
  "NEUTRALES",
  "mostrarNaves",
  "mostrarEstadisticas",
  "produccion",
  "finalizacion",
  "PLANETAS",
  "nombre",
  "naves",
  "porcentajeMuertes",
  "CONQUISTADO",
  "NEUTRAL",
  "propietario",
  "JUGADORES",
  "JUGADOR",
  "tipo",
  "HUMANO",
  "FACIL",
  "DIFICIL",
  "color",
  "MAYORQUE",
  "MENORQUE",
  "SLASH",
  "EQUAL",
  "NAME",
  "PLAYER",
  "ID",
  "INTEGER",
  "PERCENTAGE"
  };
}

