
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.zofia.parsers.timers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BRACKETC = 13;
  public static final int INT = 16;
  public static final int CURLYBRACKETC = 3;
  public static final int TIEMPOS = 4;
  public static final int COLON = 9;
  public static final int INICIO = 6;
  public static final int FIN = 7;
  public static final int EOF = 0;
  public static final int BRACKETO = 14;
  public static final int CURLYBRACKETO = 2;
  public static final int IMAGENES = 8;
  public static final int ID = 5;
  public static final int COMMA = 10;
  public static final int error = 1;
  public static final int QUOTE = 12;
  public static final int DURACION = 11;
  public static final int IDENTIFICADOR = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CURLYBRACKETO",
  "CURLYBRACKETC",
  "TIEMPOS",
  "ID",
  "INICIO",
  "FIN",
  "IMAGENES",
  "COLON",
  "COMMA",
  "DURACION",
  "QUOTE",
  "BRACKETC",
  "BRACKETO",
  "IDENTIFICADOR",
  "INT"
  };
}

