
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.zofia.parsers.colors;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREEN = 8;
  public static final int INT = 13;
  public static final int CURLYBRACKETC = 3;
  public static final int COLON = 9;
  public static final int EOF = 0;
  public static final int COLORES = 4;
  public static final int HEXCODE = 12;
  public static final int CURLYBRACKETO = 2;
  public static final int ID = 5;
  public static final int COMMA = 10;
  public static final int error = 1;
  public static final int BLUE = 7;
  public static final int HEX = 11;
  public static final int RED = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CURLYBRACKETO",
  "CURLYBRACKETC",
  "COLORES",
  "ID",
  "RED",
  "BLUE",
  "GREEN",
  "COLON",
  "COMMA",
  "HEX",
  "HEXCODE",
  "INT"
  };
}

