/* The following code was generated by JFlex 1.7.0 */

package com.zofia.lexers;
import java_cup.runtime.*;
import com.zofia.parsers.paint.sym;
import com.zofia.drivers.CanvasDriver;
import com.zofia.logic.Error;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>/home/zofia/Documents/COMPI1_XELA_2020/Proyecto Final/AnimationSoftware/src/main/java/com/zofia/lexers/PaintLexer.flex</tt>
 */
public class PaintLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\2\5\1\3\1\63\1\5\1\4\22\0\1\5\1\0\1\6"+
    "\5\0\1\52\1\53\1\7\1\61\1\54\1\62\1\10\1\11\12\2"+
    "\1\0\1\55\1\57\1\56\1\60\2\0\1\13\1\1\1\34\1\43"+
    "\1\36\3\1\1\30\4\1\1\31\1\35\1\37\1\1\1\14\1\15"+
    "\1\32\1\33\1\12\4\1\1\50\1\0\1\51\1\0\1\1\1\0"+
    "\1\27\1\23\2\1\1\26\1\41\1\22\1\45\1\16\2\1\1\25"+
    "\1\1\1\17\1\24\2\1\1\21\1\42\1\20\1\40\1\1\1\44"+
    "\3\1\1\46\1\0\1\47\7\0\1\63\113\0\1\1\37\0\1\1"+
    "\u1f36\0\1\63\1\63\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\4\1\1\1\5\1\6"+
    "\1\7\14\2\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\3\0\1\26\4\2\1\27\4\2\1\30\3\2\1\31"+
    "\1\32\1\33\1\34\1\0\1\35\1\0\2\26\1\2"+
    "\1\36\1\2\1\37\7\2\1\40\1\0\1\41\1\2"+
    "\1\42\1\2\1\43\10\2\1\44\1\45\1\46\2\2"+
    "\1\47\1\50\6\2\1\51";

  private static int [] zzUnpackAction() {
    int [] result = new int[102];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\64\0\320\0\u0104\0\64"+
    "\0\64\0\u0138\0\u016c\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270"+
    "\0\u02a4\0\u02d8\0\u030c\0\u0340\0\u0374\0\u03a8\0\64\0\64"+
    "\0\64\0\64\0\64\0\64\0\64\0\64\0\u03dc\0\u0410"+
    "\0\64\0\64\0\64\0\64\0\u0444\0\u0478\0\u04ac\0\u04e0"+
    "\0\u0514\0\u0548\0\u057c\0\u05b0\0\150\0\u05e4\0\u0618\0\u064c"+
    "\0\u0680\0\150\0\u06b4\0\u06e8\0\u071c\0\64\0\64\0\64"+
    "\0\64\0\u0750\0\64\0\u0784\0\64\0\u07b8\0\u07ec\0\150"+
    "\0\u0820\0\150\0\u0854\0\u0888\0\u08bc\0\u08f0\0\u0924\0\u0958"+
    "\0\u098c\0\u0750\0\u09c0\0\150\0\u09f4\0\150\0\u0a28\0\150"+
    "\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8\0\u0b2c\0\u0b60\0\u0b94\0\u0bc8"+
    "\0\150\0\150\0\150\0\u0bfc\0\u0c30\0\150\0\150\0\u0c64"+
    "\0\u0c98\0\u0ccc\0\u0d00\0\u0d34\0\u0d68\0\150";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[102];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\5\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\3\1\15\1\16\1\3"+
    "\1\17\2\3\1\20\2\3\1\21\1\3\1\22\4\3"+
    "\1\23\1\3\1\24\1\3\1\25\2\3\1\26\1\3"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\65\0\2\3"+
    "\7\0\34\3\20\0\1\4\5\0\1\45\56\0\1\5"+
    "\60\0\7\46\1\0\54\46\7\0\1\47\1\0\1\50"+
    "\53\0\2\3\7\0\1\3\1\51\32\3\17\0\2\3"+
    "\7\0\17\3\1\52\14\3\17\0\2\3\7\0\6\3"+
    "\1\53\25\3\17\0\2\3\7\0\5\3\1\54\21\3"+
    "\1\55\4\3\17\0\2\3\7\0\7\3\1\56\24\3"+
    "\17\0\2\3\7\0\12\3\1\57\21\3\17\0\2\3"+
    "\7\0\13\3\1\60\20\3\17\0\2\3\7\0\17\3"+
    "\1\61\14\3\17\0\2\3\7\0\2\3\1\62\31\3"+
    "\17\0\2\3\7\0\16\3\1\63\15\3\17\0\2\3"+
    "\7\0\15\3\1\64\16\3\17\0\2\3\7\0\33\3"+
    "\1\65\74\0\1\66\1\0\1\67\61\0\1\70\1\0"+
    "\1\71\13\0\1\72\53\0\6\46\1\73\55\46\7\74"+
    "\1\0\54\74\3\50\1\75\1\76\57\50\1\0\2\3"+
    "\7\0\2\3\1\77\31\3\17\0\2\3\7\0\31\3"+
    "\1\100\2\3\17\0\2\3\7\0\7\3\1\101\24\3"+
    "\17\0\2\3\7\0\6\3\1\102\25\3\17\0\2\3"+
    "\7\0\26\3\1\103\5\3\17\0\2\3\7\0\12\3"+
    "\1\104\21\3\17\0\2\3\7\0\30\3\1\105\3\3"+
    "\17\0\2\3\7\0\3\3\1\106\30\3\17\0\2\3"+
    "\7\0\17\3\1\107\14\3\17\0\2\3\7\0\13\3"+
    "\1\110\20\3\17\0\2\3\7\0\4\3\1\111\27\3"+
    "\20\0\1\112\61\0\7\74\1\113\54\74\3\0\1\75"+
    "\61\0\2\3\7\0\3\3\1\114\30\3\17\0\2\3"+
    "\7\0\4\3\1\115\27\3\17\0\2\3\7\0\14\3"+
    "\1\116\17\3\17\0\2\3\7\0\13\3\1\117\20\3"+
    "\17\0\2\3\7\0\14\3\1\120\17\3\17\0\2\3"+
    "\7\0\20\3\1\121\13\3\17\0\2\3\7\0\20\3"+
    "\1\122\13\3\17\0\2\3\7\0\30\3\1\123\3\3"+
    "\17\0\2\3\7\0\13\3\1\124\20\3\16\0\7\74"+
    "\1\113\1\74\1\75\52\74\1\0\2\3\7\0\5\3"+
    "\1\125\26\3\17\0\2\3\7\0\14\3\1\126\17\3"+
    "\17\0\2\3\7\0\2\3\1\127\31\3\17\0\2\3"+
    "\7\0\1\3\1\130\32\3\17\0\2\3\7\0\14\3"+
    "\1\131\17\3\17\0\2\3\7\0\14\3\1\132\17\3"+
    "\17\0\2\3\7\0\10\3\1\133\23\3\17\0\2\3"+
    "\7\0\15\3\1\134\16\3\17\0\2\3\7\0\21\3"+
    "\1\135\12\3\17\0\2\3\7\0\2\3\1\136\31\3"+
    "\17\0\2\3\7\0\5\3\1\137\26\3\17\0\2\3"+
    "\7\0\22\3\1\140\11\3\17\0\2\3\7\0\22\3"+
    "\1\141\11\3\17\0\2\3\7\0\16\3\1\142\15\3"+
    "\17\0\2\3\7\0\23\3\1\143\10\3\17\0\2\3"+
    "\7\0\17\3\1\144\14\3\17\0\2\3\7\0\24\3"+
    "\1\145\7\3\17\0\2\3\7\0\3\3\1\146\30\3"+
    "\16\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3484];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\2\1\2\11\15\1\10\11"+
    "\2\1\4\11\3\0\16\1\4\11\1\0\1\11\1\0"+
    "\1\11\15\1\1\0\33\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[102];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private CanvasDriver driver;
    
    public PaintLexer(java.io.Reader in, CanvasDriver driver) {
        this.zzReader = in;
        this.driver = driver;
    }

    private Symbol symbol(int type) {
        return new Symbol(type, yyline+1, yycolumn+1);
    }

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline+1, yycolumn+1, value);
    }

    private void printToken(String token){
        System.out.println(token);
    }

    private void error(String value, int line, int column) {
        Error error = new Error(line, column, "Lexico", "Elemento lexico desconocido: '" + yytext() + "'");
        driver.getErrors().add(error);
    }
    
    private void invalid_symbol(String message) {
        System.out.println(message);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public PaintLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 200) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new java.lang.Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { printToken("ERROR: " + yytext()); 
                                  error(yytext(), yyline+1, yycolumn+1);
            } 
            // fall through
          case 42: break;
          case 2: 
            { printToken("Id: " + yytext()); return symbol(sym.ID, yytext());
            } 
            // fall through
          case 43: break;
          case 3: 
            { printToken(yytext()); return symbol(sym.INTEGER, Integer.parseInt(yytext()));
            } 
            // fall through
          case 44: break;
          case 4: 
            { /*do nothing*/
            } 
            // fall through
          case 45: break;
          case 5: 
            { printToken("*"); return symbol(sym.STAR, "*");
            } 
            // fall through
          case 46: break;
          case 6: 
            { printToken("."); return symbol(sym.DOT, ".");
            } 
            // fall through
          case 47: break;
          case 7: 
            { printToken("/"); return symbol(sym.DIAGONAL, "/");
            } 
            // fall through
          case 48: break;
          case 8: 
            { printToken("{"); return symbol(sym.CURLYBRACKETO, "{");
            } 
            // fall through
          case 49: break;
          case 9: 
            { printToken("}"); return symbol(sym.CURLYBRACKETC, "}");
            } 
            // fall through
          case 50: break;
          case 10: 
            { printToken("["); return symbol(sym.BRACKETO, "[");
            } 
            // fall through
          case 51: break;
          case 11: 
            { printToken("]"); return symbol(sym.BRACKETC, "]");
            } 
            // fall through
          case 52: break;
          case 12: 
            { printToken("("); return symbol(sym.PARENTHESISO, "(");
            } 
            // fall through
          case 53: break;
          case 13: 
            { printToken(")"); return symbol(sym.PARENTHESISC, ")");
            } 
            // fall through
          case 54: break;
          case 14: 
            { printToken(","); return symbol(sym.COMMA, ",");
            } 
            // fall through
          case 55: break;
          case 15: 
            { printToken(";"); return symbol(sym.SEMICOLON, ";");
            } 
            // fall through
          case 56: break;
          case 16: 
            { printToken("="); return symbol(sym.EQUAL, "=");
            } 
            // fall through
          case 57: break;
          case 17: 
            { printToken("<"); return symbol(sym.LESSTHAN, "<");
            } 
            // fall through
          case 58: break;
          case 18: 
            { printToken(">"); return symbol(sym.GREATERTHAN, ">");
            } 
            // fall through
          case 59: break;
          case 19: 
            { printToken("+"); return symbol(sym.PLUS, "+");
            } 
            // fall through
          case 60: break;
          case 20: 
            { printToken("-"); return symbol(sym.MINUS, "-");
            } 
            // fall through
          case 61: break;
          case 21: 
            { invalid_symbol("Simbolo invalido <"+ yytext()+">");
            } 
            // fall through
          case 62: break;
          case 22: 
            { printToken("Comment: " + yytext()); /*Do nothing*/
            } 
            // fall through
          case 63: break;
          case 23: 
            { printToken("if"); return symbol(sym.IF, "if");
            } 
            // fall through
          case 64: break;
          case 24: 
            { printToken("OR"); return symbol(sym.OR, "OR");
            } 
            // fall through
          case 65: break;
          case 25: 
            { printToken("=="); return symbol(sym.SAME, "==");
            } 
            // fall through
          case 66: break;
          case 26: 
            { printToken("=>"); return symbol(sym.GREATEREQUAL, ">=");
            } 
            // fall through
          case 67: break;
          case 27: 
            { printToken("<="); return symbol(sym.LESSEQUAL, "<=");
            } 
            // fall through
          case 68: break;
          case 28: 
            { printToken("<>"); return symbol(sym.BETWEEN, "<>");
            } 
            // fall through
          case 69: break;
          case 29: 
            { printToken("cadena: " + yytext()); return symbol(sym.STRING_, yytext());
            } 
            // fall through
          case 70: break;
          case 30: 
            { printToken("AND"); return symbol(sym.AND, "AND");
            } 
            // fall through
          case 71: break;
          case 31: 
            { printToken("int"); return symbol(sym.INT, "int");
            } 
            // fall through
          case 72: break;
          case 32: 
            { printToken("rank: " + yytext()); return symbol(sym.RANK, yytext());
            } 
            // fall through
          case 73: break;
          case 33: 
            { printToken("VARS"); return symbol(sym.VARS, "VARS");
            } 
            // fall through
          case 74: break;
          case 34: 
            { printToken("true"); return symbol(sym.TRUE, "true");
            } 
            // fall through
          case 75: break;
          case 35: 
            { printToken("else"); return symbol(sym.ELSE, "else");
            } 
            // fall through
          case 76: break;
          case 36: 
            { printToken("false"); return symbol(sym.FALSE, "false");
            } 
            // fall through
          case 77: break;
          case 37: 
            { printToken("while"); return symbol(sym.WHILE, "while");
            } 
            // fall through
          case 78: break;
          case 38: 
            { printToken("String"); return symbol(sym.STRING, "String");
            } 
            // fall through
          case 79: break;
          case 39: 
            { printToken("PINTAR"); return symbol(sym.PINTAR, "PINTAR");
            } 
            // fall through
          case 80: break;
          case 40: 
            { printToken("boolean"); return symbol(sym.BOOLEAN, "boolean");
            } 
            // fall through
          case 81: break;
          case 41: 
            { printToken("INSTRUCCIONES"); return symbol(sym.INSTRUCCIONES, "INSTRUCCIONES");
            } 
            // fall through
          case 82: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  private String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = sym.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java PaintLexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        PaintLexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new PaintLexer(reader);
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
