
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.zofia.parsers.queries;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 9;
  public static final int SEMICOLON = 17;
  public static final int INSERTAR = 4;
  public static final int OR = 10;
  public static final int MENORIGUAL = 13;
  public static final int EQUAL = 16;
  public static final int COLUMN = 18;
  public static final int ELIMINAR = 7;
  public static final int MAYORQUE = 12;
  public static final int FILTRAR = 3;
  public static final int VALORES = 23;
  public static final int ASIGNAR = 6;
  public static final int ACTUALIZAR = 5;
  public static final int COMMA = 24;
  public static final int NUMBER = 25;
  public static final int EOF = 0;
  public static final int MENORQUE = 11;
  public static final int MAYORIGUAL = 14;
  public static final int error = 1;
  public static final int CPARENTESIS = 22;
  public static final int ASSIGNATION = 20;
  public static final int EN = 8;
  public static final int DIFERENTEDE = 15;
  public static final int OPARENTESIS = 21;
  public static final int PATH = 19;
  public static final int SELECCIONAR = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELECCIONAR",
  "FILTRAR",
  "INSERTAR",
  "ACTUALIZAR",
  "ASIGNAR",
  "ELIMINAR",
  "EN",
  "AND",
  "OR",
  "MENORQUE",
  "MAYORQUE",
  "MENORIGUAL",
  "MAYORIGUAL",
  "DIFERENTEDE",
  "EQUAL",
  "SEMICOLON",
  "COLUMN",
  "PATH",
  "ASSIGNATION",
  "OPARENTESIS",
  "CPARENTESIS",
  "VALORES",
  "COMMA",
  "NUMBER"
  };
}

